### ISSUE TITLE
When updating an expectation score, the expectation status doesn't change

### ISSUE THREAD

**Issue by jborozco** [OpenAEV-Platform/openaev#1350]
## Description

Expectation status should be updated to failed if the score is updated 
![image](https://github.com/user-attachments/assets/067396cf-72c5-4143-8ff8-8d01ebf3b952)

## Reproducible Steps

1. go to https://testing.obas.staging.filigran.io/admin/exercises/96892d44-ce23-4045-9fe4-68a9d849a0b9/injects/d17fa25c-21e5-49ff-a78c-4da9ea9c46f2
2. modify expectation score to 90

## Expected Output

the status should be "failed" 

## Actual Output

The status is still "success"

**Comment by MarineLeM** [comment]
I found 2 other problems on this topics. Here are the two use cases:

**_Problem 1 :_**
Prerequisite : Set the inject expectation mode to 'at least one player need to validate'  with an expected score of 80. Assign team with at least one player 
Observation : if you set the score to more than 0 the inject expectation status will always be 'Success'
Expected Output : If the score is set below the expected score (80 in this example) the status should be 'Failed'

**_Problem 2 :_**
Prerequisite : Set the inject expectation mode to 'all players need to validate' with an expected score of 80. Assign a team with 2 players.
Observation : if you set the score of first player to 79 and the score of the second player to 100. The inject expectation status for the team shows as 'Success.'
Expected Output : The inject expectation status for the team should be 'failed' because one of the players did not meet the expected score, even though the average score of the two players is higher than the expected score.
