### ISSUE TITLE
Inject: Broken filter for the ATT&CK matrix

### ISSUE THREAD

**Issue by marckto-filigran** [OpenAEV-Platform/openaev#950]
## Description

From the ATT&CK Matrix, when you add a filter, the number of result has nothing to do with what is displayed.

## Environment

4. Other environment details: https://demo.obas.filigran.io/

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a scenario
2. Add an inject, click on ATT&CK
3. Select one technique for example  T1583 > 8
![image](https://github.com/OpenBAS-Platform/openbas/assets/166409476/4ebba847-3816-4bc4-a944-62ff20238a8c)

## Expected Output

8 results

## Actual Output

no result
![image](https://github.com/OpenBAS-Platform/openbas/assets/166409476/67f71b2e-cbd2-4aaa-833e-176e3291a394)

## Additional information

Another example with T1559 (3)
6 results
![image](https://github.com/OpenBAS-Platform/openbas/assets/166409476/5391f796-3d3b-4e08-8247-ef7ff901d5a2)

**Comment by RomuDeuxfois** [comment]
The number in parentheses is not the number of results but the number of existing sub-techniques
There is a need to reflect on this information to be displayed which is not clear to the user @jborozco

**Comment by jborozco** [comment]
@RomuDeuxfois 

Since we don't have sub-techniques visible yet, we can show here the number of available injects to be clearer. 

To avoid unecessary clicks it would be great to deactivate all attack patterns without injects for the MITRE filter 

I will create a feature ticket about being able to select sub techniques in the MITRE filter so we can cover this case too
